config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  root to: 'homes#top'
  resources :books
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/book.rb
class Book < ApplicationRecord
  validates :title, presence: true
  validates :body, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/books_controller.rb
class BooksController < ApplicationController
  def index
    @books_all = Book.all
    @book = Book.new

  end

  def show
    @book = Book.find(params[:id])

  end

  def edit
    @books_all = Book.all
    @edit = Book.new
    @book = Book.find(params[:id])
  end

  def update
    @book = Book.find(params[:id])
    if @book.update(book_params)
      flash[:notice] = "Book was successfully created."
      redirect_to book_path(@book.id)
    else
      render :edit
    end
  end

  def destroy
    @book = Book.find(params[:id])
    @book.destroy
    redirect_to '/books'
  end

  def create
    @book = Book.new(book_params)
    if @book.save
      flash[:notice] = "Book was successfully created."
      redirect_to book_path(@book.id)
    else
      @books_all = Book.all
      render :index
    end
  end

  def book_params
    params.require(:book).permit(:title, :body)
  end
end

app/controllers/homes_controller.rb
class HomesController < ApplicationController
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/books_helper.rb
module BooksHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/views/books/edit.html.erb
    <head></head>
    <body>
        <h1>Editing Book</h1>
        <% if @book.errors.any? %>
         <%= @book.errors.count %>errors prohibited this book from being saved
         <ul>
        <% @book.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
         </ul>
    <% end %>
        <%= form_with model: @book do |f| %>

            <%= form_with model: @book do |f| %>
            <p>Title</p>
            <%= f.text_field :title %>

            <p>Body</p>
            <%= f.text_area :body %>

            <%= f.submit 'Update Book' %>
            <% end %>
        <% end %>
    </body>

    <footer>
        <%= link_to 'Show', book_path(@book.id) %> | <%= link_to 'Back', books_path %>
    </footer>

app/views/books/index.html.erb
<h1>Books</h1>
<table>
  <thead>
    <tr>
      <th>Title</th>
      <th>Body</th>
      <th colspan="3"></th>
    </tr>
  </thead>

<% @books_all.each do |book| %>
<tbody>
  <tr>
    <td><%= book.title %></td>
    <td><%= book.body %></td>
    <td><%= link_to 'show', book_path(book.id) %></td>
    <td><%= link_to 'edit', edit_book_path(book.id) %></td>
    <td><%= link_to 'Destroy', book_path(book.id), method: :delete, "data-confirm" => "Are you sure?" %></td>
  </tr>

<% end %>
</tbody>

</table>

<h2>New book</h2>
<% if @book.errors.any? %>
  <%= @book.errors.count %>errors prohibited this book from being saved
  <ul>
    <% @book.errors.full_messages.each do |message| %>
      <li><%= message %></li>
    <% end %>
  </ul>
<% end %>

<%= form_with model: Book.new do |f| %>
  <h4><%= @title %></h4>
  <%= f.text_field :title %>
  <h4><%= @body %></h4>
  <%= f.text_area :body %>

  <%= f.submit 'Create Book' %>

<% end %>

app/views/books/show.html.erb
<table>

    <tbody>
        <%= flash[:notice] %>
        <tr>
            <td>
            <strong>Title:</strong>
            <%= @book.title %>
            </td>
        </tr>

        <tr>
            <td>
            <strong>Body:</strong>
            <%= @book.body %>
            </td>
        </tr>

    </tbody>

    <tfooter>
        <tr>
        <td><%= link_to 'Edit', edit_book_path(@book.id) %> | <%= link_to 'Back', books_path %></td>
        </tr>
    </tfooter>


</table>

app/views/homes/top.html.erb
<html>

  <head></head>

  <body>
    <h1>ようこそ
    <strong><%= @title %></strong>
    へ！
    </h1>

      <p><strong><%= @title %></strong>では、さまざまな書籍に関するあなたの意見や</p>

      <p>印象を共有し交換することができます</p>

      <p><%= link_to 'start', books_path %></p>

  </body>

</html>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Bookers</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>